### ISSUE TITLE
Preview styles are affecting the admin bar

### ISSUE THREAD

**Issue by ryelle** [WordPress/pattern-directory#513]
After an update to GB 13.9, the admin bar now has a max-width of 800px.

![image](https://user-images.githubusercontent.com/541093/185421424-75ad41c5-a39a-4441-bbca-3fce64e63d94.png)

The offending style is the `body > div > :where…` from here, which is generated as part of "Core styles: block-supports".

```css
.entry-content > :where(:not(.alignleft):not(.alignright):not(.alignfull)),
body > div > :where(:not(.alignleft):not(.alignright):not(.alignfull)) {
  max-width: 800px;
  margin-left: auto !important;
  margin-right: auto !important;
}
```

This style is set up [in the theme here](https://github.com/WordPress/pattern-directory/blob/b6b320cc3b119cfaa6786d9bd4d400466361c9bf/public_html/wp-content/themes/pattern-directory/functions.php#L157), but in previous GB versions, this only output as the `window.__editorStyles` value passed into the pattern previews. Somehow it's being cached(?) and also output along with the regular theme layout styles.

This is probably the issue, `WP_Style_Engine::store_css_rule(…`: https://github.com/WordPress/gutenberg/blob/29d6801902ad97f749ccadd789a23b2d97369e3e/packages/style-engine/class-wp-style-engine.php#L613
